version: "3.0"
services:
  littlelink-server:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Kieran Robson
      - META_DESCRIPTION=Kieran Robson Link page
      - META_AUTHOR=Kieran Robson
      - META_KEYWORDS=HomeLab, CSS, HTML, Engineering
      - LANG=en
      - META_INDEX_STATUS=all
      - THEME=Dark
      - FAVICON_URL=
      - AVATAR_URL=
      - AVATAR_2X_URL=
      - NAME=Kieran Robson
      - BIO=Open Source List contributor | Tech Nerd | Self Hosting Noob | Discord Bot Developer
      - FOOTER=Thanks for stopping by!
      - BUTTON_ORDER=GITHUB,DISCORD,TWITTER,SPORIFY,LETTERBOXD,TRAKT,LASTFM,STEAM
      - GITHUB=https://github.com/KieranRobson
      - DISCORD=https://discord.gg/QvrG4xPGKZ
      - TWITTER=https://twitter.com/Kieranr27
      - SPOTIFY=https://open.spotify.com/user/r10ocx4jtipe2wcc77xb9pvu3
      - STEAM=https://steamcommunity.com/id/R0BB0568
      - LETTERBOXD=https://letterboxd.com/kieranr27/
      - TRAKT=https://trakt.tv/users/kieranr27
      - LASTFM=https://last.fm/user/kieranr27/
    ports:
      - 7000:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true